name: Update GTFS Feed

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  schedule:
    - cron: '0 2 * * 0' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run GTFS generator script
        run: python main.py

      - name: Commit and push generated ZIP
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
          git add andorra_gtfs.zip
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace GTFS dat" && git push)
